version: '3.1'
services:
  bookmedik:
    container_name: bookmedik-app
    image: evanticks/app-examen
    restart: always
    environment:
      DB_USER: app
      DB_PASSWORD: app
      ENV DB_HOST: mariadb_app
      NOMBRE_DB: app
    ports:
      - 8084:80
    depends_on:
      - db
  db:
    container_name: mariadb_app
    image: mariadb:10.5
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: app
      MARIADB_USER: app
      MARIADB_PASSWORD: app
    volumes:
      - mariadb_data:/var/lib/mysql
volumes:
    mariadb_data:
